title: Sandbox
description: Blog about technology and society
url: "https://blog.chandninaidu.com"
baseurl: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-persephone

# Plugins
plugins:
  - jekyll-feed
